name: Smaug
version: '1.1'
main: org.aincraft.SmaugBootstrap
api-version: '1.21'
authors: [ mintychochip ]
commands:
  smith:
    description: test
  test:
    description: test
  sreload:
    description: reloads